# Generated by Django 4.2.7 on 2024-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookEaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
