# Generated by Django 4.2.7 on 2024-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookEaseApp', '0003_alter_bus_arrival_time_alter_bus_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
